name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src\Sigurn.CommandLine.sln
    - name: Build Debug
      run: dotnet build --no-restore src\Sigurn.CommandLine.sln
    - name: Build Release
      run: dotnet build --no-restore -c Release src\Sigurn.CommandLine.sln
    - name: Test Debug
      run: dotnet test --no-build --verbosity normal  src\Sigurn.CommandLine.sln
    - name: Test Release
      run: dotnet test --no-build --verbosity normal -c Release src\Sigurn.CommandLine.sln
